### ISSUE TITLE
Could not load type 'TenantClass' 

### ISSUE THREAD

**Issue by dev-day** [netjson/netjson#66]
Hi,

When I compile the web app, on first click, I get this error.
Refreshing, the error goes away for good.

Could not load type 'TenantClass' from assembly 'NetJSONGeneratedAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

When I restart the app, the error comes back once, and then goes away again after refresh.

Is there a specific setting I need to apply to prevent this?

Regards,
Dev

**Comment by nemesisdesign** [comment]
what are you referring to? This does not look like something that has to do with this project.

**Comment by dev-day** [comment]
Yes, you're right - it's https://github.com/rpgmaker/NetJSON that I was after!

Thanks for your reponse.
